-- 创建数据库
CREATE DATABASE IF NOT EXISTS course_db DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE course_db;

-- 用户表
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    nickname VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 课程表
CREATE TABLE IF NOT EXISTS course (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    teacher VARCHAR(50),
    classroom VARCHAR(50),
    weekday VARCHAR(10),
    time_slot VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 考试表
CREATE TABLE IF NOT EXISTS exam (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    course_id BIGINT,
    name VARCHAR(200) NOT NULL,
    exam_date DATETIME,
    location VARCHAR(100),
    remark VARCHAR(500),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 作业表
CREATE TABLE IF NOT EXISTS homework (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    course_id BIGINT,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    deadline DATETIME,
    status TINYINT DEFAULT 0 COMMENT '0-未完成 1-已完成',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 知识点表
CREATE TABLE IF NOT EXISTS knowledge_point (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    course_id BIGINT,
    parent_id BIGINT DEFAULT 0 COMMENT '0=章节 非0=归属某章节的知识点',
    title VARCHAR(200) NOT NULL,
    content TEXT,
    tags VARCHAR(200),
    status TINYINT DEFAULT 0 COMMENT '0-未学习 1-学习中 2-已掌握',
    sort_order INT DEFAULT 0,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
